# Generated by Django 2.2.5 on 2021-01-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16, null=True)),
                ('worker', models.CharField(max_length=16, null=True)),
                ('problem', models.TextField(default='', null=True)),
                ('solution', models.TextField(default='', null=True)),
                ('banzu', models.CharField(max_length=16, null=True)),
                ('diaodu', models.CharField(max_length=16, null=True)),
                ('laiyuan', models.CharField(max_length=16, null=True)),
                ('yanshouren', models.CharField(max_length=16, null=True)),
                ('wancheng', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
