# Generated by Django 2.2.5 on 2021-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Require',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=32, null=True)),
                ('product_type', models.CharField(max_length=32, null=True)),
                ('product_code', models.CharField(max_length=32, null=True)),
                ('date', models.CharField(max_length=32, null=True)),
                ('place', models.CharField(max_length=32, null=True)),
                ('condition', models.TextField(default='', null=True)),
                ('nandian', models.TextField(default='', null=True)),
                ('attention', models.TextField(default='', null=True)),
                ('inputfile', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
